### ISSUE TITLE
Unable to install anything using pip after upgrade to 21.0 

### ISSUE THREAD

**Issue by gbloquel** [claranet/boto-sts-assume-role#1]
Environment

    pip version: 21.0.1
    Python version: 3.8.2
    OS: Ubuntu 20.04

Description

After upgrading to 21.0.1 it is unable to install the package.

Output

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /home/runner/work/boto-sts-assume-role/boto-sts-assume-role
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/2.7.18/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-Qvu2g0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-Qvu2g0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-JQKMGc
         cwd: /tmp/pip-req-build-Qvu2g0/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-Qvu2g0/setup.py", line 29, in <module>
        install_requires=[str(ir.req) for ir in requirements],
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
